### ISSUE TITLE
Discord canary with BBD thinks I'm using a browser

### ISSUE THREAD

**Issue by emberglazee** [rauenzi/BBDInstaller#26]
when bbd stopped working with ptb, i uninstalled the ptb version and installed the canary one, but whenever betterdiscord starts with it, discord thinks im using a browser. because of that i cant do some things like streaming. and the betterdiscord settings dont even show up in discord settings

**Comment by emberglazee** [comment]
oh and i cant move the discord window anymore, and there are no "minimize, maximize and close" buttons anymore, just gone

edit: i can still resize the window though and move it with win+arrow keys

**Comment by tealyt** [comment]
NoName thats a problem with all discord distros. the program just flat out broke

**Comment by AshOnDiscord** [comment]
Have you guys found a fix or nah?

**Comment by whypet** [comment]
does anyone know a fix? i've been looking for an answer weeks ago, i found out that it might be the scripts that the installer injects into discord as i tried to fix the paths manually in the code from appdata to localappdata because of the latest update, but it didn't seem to help with anything. i have also noticed module folder names had a suffix with a hyphen and a random digit too (example is "discord_rpc-1" in `%localappdata%\DiscordCanary\app-1.0.27\modules`)

**Comment by jbuny-jui** [comment]
any fix yet?

**Comment by zerebos** [comment]
This repository is now deprecated in favor of https://github.com/BetterDiscord/Installer
